// Multi-tenant database types for Folks
// These will be auto-generated by Supabase CLI later,
// but we define the core types for development.

export type UserRole = "super_admin" | "admin" | "consejo" | "residente" | "personal" | "portero";

export type PaymentStatus = "pending" | "paid" | "overdue" | "cancelled";

export type PackageStatus = "received" | "notified" | "delivered";

export type TicketStatus = "open" | "in_progress" | "resolved" | "rated";

export type TicketCategory =
  | "maintenance"
  | "noise"
  | "security"
  | "billing"
  | "common_areas"
  | "parking"
  | "pets"
  | "suggestion"
  | "other";

export type TicketPriority = "low" | "medium" | "high" | "urgent";

export type ReservationStatus =
  | "pending"
  | "confirmed"
  | "cancelled"
  | "completed";

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  primary_color: string;
  secondary_color: string;
  address: string;
  city: string;
  department: string;
  nit: string | null;
  admin_email: string;
  admin_phone: string | null;
  total_units: number;
  created_at: string;
  updated_at: string;
}

export interface Unit {
  id: string;
  tenant_id: string;
  tower: string;
  apartment: string;
  cadastral_number: string | null;
  area_m2: number | null;
  parking_spot: string | null;
  admin_fee_cop: number;
  created_at: string;
}

export interface Resident {
  id: string;
  tenant_id: string;
  unit_id: string;
  user_id: string | null;
  full_name: string;
  document_type: "cc" | "ce" | "passport";
  document_number: string;
  email: string | null;
  phone: string | null;
  role: UserRole;
  is_owner: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Vehicle {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  plate: string;
  type: "car" | "motorcycle" | "bicycle";
  color: string | null;
  brand: string | null;
  parking_spot: string | null;
  created_at: string;
}

export interface Pet {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  name: string;
  species: "dog" | "cat" | "other";
  breed: string | null;
  vaccination_up_to_date: boolean;
  created_at: string;
}

export interface Zone {
  id: string;
  tenant_id: string;
  name: string;
  description: string | null;
  icon: string | null;
  photo_url: string | null;
  price_cop: number;
  max_duration_hours: number;
  max_guests: number;
  max_reservations_per_month: number;
  is_active: boolean;
  schedule: ZoneSchedule;
  created_at: string;
}

export interface ZoneSchedule {
  [day: string]: { open: string; close: string } | null;
}

export interface Reservation {
  id: string;
  tenant_id: string;
  zone_id: string;
  unit_id: string;
  resident_id: string;
  date: string;
  start_time: string;
  end_time: string;
  guests_count: number;
  status: ReservationStatus;
  payment_id: string | null;
  notes: string | null;
  created_at: string;
}

export interface ReservationGuest {
  id: string;
  reservation_id: string;
  full_name: string;
  document_number: string | null;
  created_at: string;
}

export interface Payment {
  id: string;
  tenant_id: string;
  unit_id: string;
  concept: "admin_fee" | "zone_reservation" | "penalty" | "other";
  description: string | null;
  amount_cop: number;
  due_date: string;
  paid_at: string | null;
  status: PaymentStatus;
  payment_ref: string | null;
  wompi_transaction_id: string | null;
  receipt_url: string | null;
  late_fee_cop: number;
  created_at: string;
}

export interface Package {
  id: string;
  tenant_id: string;
  unit_id: string;
  description: string;
  photo_url: string | null;
  received_by: string;
  received_at: string;
  delivered_at: string | null;
  delivered_to: string | null;
  signature_url: string | null;
  status: PackageStatus;
  created_at: string;
}

export interface Announcement {
  id: string;
  tenant_id: string;
  title: string;
  body: string;
  category: "general" | "maintenance" | "billing" | "event" | "emergency";
  created_by: string;
  is_pinned: boolean;
  attachments: string[];
  created_at: string;
  updated_at: string;
}

export interface Notification {
  id: string;
  tenant_id: string;
  user_id: string;
  type: "package" | "payment" | "announcement" | "visitor" | "reservation" | "pqr";
  title: string;
  body: string;
  data: Record<string, unknown>;
  read: boolean;
  created_at: string;
}

export interface Ticket {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  category: TicketCategory;
  priority: TicketPriority;
  subject: string;
  description: string;
  status: TicketStatus;
  rating: number | null;
  rated_at: string | null;
  assigned_to: string | null;
  scheduled_date: string | null;
  created_at: string;
  updated_at: string;
  resolved_at: string | null;
}

export interface TicketMessage {
  id: string;
  ticket_id: string;
  tenant_id: string;
  sender_id: string;
  message: string;
  attachments: string[];
  created_at: string;
}

export interface Visitor {
  id: string;
  tenant_id: string;
  unit_id: string;
  authorized_by: string;
  full_name: string;
  document_number: string | null;
  phone: string | null;
  reason: string | null;
  is_favorite: boolean;
  group_name: string | null;
  authorized_until: string | null;
  expires_at: string | null;
  photo_url: string | null;
  vehicle_plate: string | null;
  arrived_at: string | null;
  left_at: string | null;
  created_at: string;
}

// ============================================
// Access Control (MOD-008)
// ============================================

export type AccessAction = "entry" | "exit" | "denied";

export type AccessMethod = "manual" | "qr" | "app" | "whatsapp";

export type ContactRelationship = "family" | "friend" | "service" | "delivery";

export interface AccessLog {
  id: string;
  tenant_id: string;
  visitor_id: string | null;
  unit_id: string | null;
  action: AccessAction;
  method: AccessMethod;
  registered_by: string | null;
  notes: string | null;
  created_at: string;
}

export interface FrequentContact {
  id: string;
  tenant_id: string;
  resident_id: string;
  name: string;
  document: string | null;
  phone: string | null;
  relationship: ContactRelationship | null;
  photo_url: string | null;
  is_favorite: boolean;
  created_at: string;
}

// ============================================
// Financial Dashboard (MOD-006)
// ============================================

export type ExpenseCategory =
  | "maintenance"
  | "security"
  | "utilities"
  | "cleaning"
  | "insurance"
  | "payroll"
  | "legal"
  | "reserve_fund"
  | "extraordinary"
  | "other";

export type ExpenseStatus = "pending" | "approved" | "rejected" | "paid";

export type BudgetPeriodStatus = "draft" | "approved" | "active" | "closed";

export type UtilityType =
  | "agua"
  | "energia"
  | "gas"
  | "internet"
  | "telefono"
  | "aseo";

export type ReserveMovementType = "income" | "expense";

export interface Expense {
  id: string;
  tenant_id: string;
  category: ExpenseCategory;
  subcategory: string | null;
  description: string;
  amount_cop: number;
  expense_date: string;
  vendor: string | null;
  receipt_url: string | null;
  status: ExpenseStatus;
  requested_by: string | null;
  approved_by: string | null;
  second_approved_by: string | null;
  approved_at: string | null;
  paid_at: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface UtilityBill {
  id: string;
  tenant_id: string;
  utility_type: UtilityType;
  provider: string | null;
  bill_period: string | null;
  amount_cop: number;
  due_date: string | null;
  paid_at: string | null;
  receipt_url: string | null;
  notes: string | null;
  created_at: string;
}

export interface BudgetPeriod {
  id: string;
  tenant_id: string;
  name: string;
  start_date: string;
  end_date: string;
  total_income_cop: number;
  total_expense_cop: number;
  status: BudgetPeriodStatus;
  created_at: string;
  updated_at: string;
}

export interface BudgetItem {
  id: string;
  budget_period_id: string;
  tenant_id: string;
  category: ExpenseCategory;
  description: string;
  budgeted_cop: number;
  executed_cop: number;
  created_at: string;
  updated_at: string;
}

export interface ReserveFundMovement {
  id: string;
  tenant_id: string;
  type: ReserveMovementType;
  amount_cop: number;
  description: string;
  reference_id: string | null;
  movement_date: string;
  balance_after_cop: number | null;
  created_at: string;
}

export interface PortfolioUnit {
  tenant_id: string;
  unit_id: string;
  tower: string;
  apartment: string;
  admin_fee_cop: number;
  overdue_count: number;
  pending_count: number;
  overdue_total: number;
  pending_total: number;
  oldest_overdue_date: string | null;
  overdue_0_30: number;
  overdue_31_60: number;
  overdue_61_90: number;
  overdue_90_plus: number;
}

export interface FinancialSummary {
  totalIncome: number;
  totalExpenses: number;
  balance: number;
  collectionRate: number;
  totalOverdue: number;
  overdueUnitsCount: number;
  reserveFundBalance: number;
}

// ============================================
// Assemblies AI (MOD-013)
// ============================================

export type AssemblyType = "ordinary" | "extraordinary";

export type AssemblyStatus =
  | "scheduled"
  | "in_progress"
  | "transcribing"
  | "generating"
  | "review"
  | "published";

export type ConvocationType = "first" | "second" | "universal";

export type AttendeeRole = "owner" | "delegate" | "tenant";

export type CommitmentStatus = "pending" | "in_progress" | "completed" | "overdue";

export interface Assembly {
  id: string;
  tenant_id: string;
  title: string;
  type: AssemblyType;
  date: string;
  location: string | null;
  convocation_type: ConvocationType | null;
  quorum_required: number | null;
  quorum_present: number | null;
  total_units: number | null;
  units_present: number | null;
  status: AssemblyStatus;
  audio_url: string | null;
  transcript: string | null;
  minutes_html: string | null;
  minutes_pdf_url: string | null;
  president: string | null;
  secretary: string | null;
  created_by: string | null;
  published_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface AssemblyAttendee {
  id: string;
  assembly_id: string;
  tenant_id: string;
  resident_id: string | null;
  unit_id: string | null;
  full_name: string;
  role: AttendeeRole;
  coefficient: number | null;
  signature_url: string | null;
  checked_in_at: string;
}

export interface AgendaItem {
  id: string;
  assembly_id: string;
  tenant_id: string;
  position: number;
  title: string;
  description: string | null;
  discussion_summary: string | null;
  decision: string | null;
  vote_for: number;
  vote_against: number;
  vote_abstain: number;
  created_at: string;
}

export interface Commitment {
  id: string;
  assembly_id: string;
  tenant_id: string;
  title: string;
  description: string | null;
  responsible: string | null;
  responsible_id: string | null;
  due_date: string | null;
  status: CommitmentStatus;
  progress: number;
  completed_at: string | null;
  created_at: string;
  updated_at: string;
}

// ============================================
// Gamification (MOD-010)
// ============================================

export type PointLevel = "bronce" | "plata" | "oro" | "platino";

export type PointTransactionType = "earn" | "spend" | "expire";

export type PointReason =
  | "payment_ontime"
  | "pqr_created"
  | "assembly_attended"
  | "reservation"
  | "redeem_discount";

export interface ResidentPoints {
  id: string;
  tenant_id: string;
  resident_id: string;
  points: number;
  level: PointLevel;
  total_earned: number;
  total_spent: number;
  created_at: string;
  updated_at: string;
}

export interface PointTransaction {
  id: string;
  tenant_id: string;
  resident_id: string;
  type: PointTransactionType;
  amount: number;
  reason: PointReason;
  reference_id: string | null;
  created_at: string;
}

export interface Badge {
  id: string;
  tenant_id: string;
  name: string;
  description: string;
  icon: string;
  requirement: string;
  points_reward: number;
  created_at: string;
}

export interface ResidentBadge {
  id: string;
  tenant_id: string;
  resident_id: string;
  badge_id: string;
  earned_at: string;
}

// ============================================
// Voting (MOD-014)
// ============================================

export type PollType = "simple" | "multiple" | "weighted";

export type PollStatus = "draft" | "open" | "closed" | "cancelled";

export interface Poll {
  id: string;
  tenant_id: string;
  assembly_id: string | null;
  title: string;
  description: string | null;
  type: PollType;
  status: PollStatus;
  requires_quorum: boolean;
  quorum_percentage: number;
  restricted: boolean;
  opens_at: string | null;
  closes_at: string | null;
  created_by: string | null;
  created_at: string;
}

export interface PollOption {
  id: string;
  poll_id: string;
  tenant_id: string;
  label: string;
  position: number;
  created_at: string;
}

export interface Vote {
  id: string;
  poll_id: string;
  option_id: string;
  tenant_id: string;
  resident_id: string;
  unit_id: string | null;
  coefficient: number | null;
  created_at: string;
}

// ============================================
// Staff Shifts (MOD-015)
// ============================================

export type StaffRole = "portero" | "aseo" | "mantenimiento" | "seguridad";

export type ShiftStatus = "scheduled" | "in_progress" | "completed" | "absent";

export interface StaffShift {
  id: string;
  tenant_id: string;
  staff_name: string;
  role: StaffRole;
  shift_date: string;
  start_time: string;
  end_time: string;
  status: ShiftStatus;
  check_in_at: string | null;
  check_out_at: string | null;
  notes: string | null;
  created_at: string;
}
