// Multi-tenant database types for Folks
// These will be auto-generated by Supabase CLI later,
// but we define the core types for development.

export type UserRole = "admin" | "residente" | "portero" | "super_admin";

export type PaymentStatus = "pending" | "paid" | "overdue" | "cancelled";

export type PackageStatus = "received" | "notified" | "delivered";

export type TicketStatus = "open" | "in_progress" | "resolved" | "rated";

export type ReservationStatus =
  | "pending"
  | "confirmed"
  | "cancelled"
  | "completed";

export interface Tenant {
  id: string;
  name: string;
  slug: string;
  logo_url: string | null;
  primary_color: string;
  secondary_color: string;
  address: string;
  city: string;
  department: string;
  nit: string | null;
  admin_email: string;
  admin_phone: string | null;
  total_units: number;
  created_at: string;
  updated_at: string;
}

export interface Unit {
  id: string;
  tenant_id: string;
  tower: string;
  apartment: string;
  cadastral_number: string | null;
  area_m2: number | null;
  parking_spot: string | null;
  admin_fee_cop: number;
  created_at: string;
}

export interface Resident {
  id: string;
  tenant_id: string;
  unit_id: string;
  user_id: string | null;
  full_name: string;
  document_type: "cc" | "ce" | "passport";
  document_number: string;
  email: string | null;
  phone: string | null;
  role: UserRole;
  is_owner: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Vehicle {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  plate: string;
  type: "car" | "motorcycle" | "bicycle";
  color: string | null;
  brand: string | null;
  parking_spot: string | null;
  created_at: string;
}

export interface Pet {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  name: string;
  species: "dog" | "cat" | "other";
  breed: string | null;
  vaccination_up_to_date: boolean;
  created_at: string;
}

export interface Zone {
  id: string;
  tenant_id: string;
  name: string;
  description: string | null;
  icon: string | null;
  photo_url: string | null;
  price_cop: number;
  max_duration_hours: number;
  max_guests: number;
  max_reservations_per_month: number;
  is_active: boolean;
  schedule: ZoneSchedule;
  created_at: string;
}

export interface ZoneSchedule {
  [day: string]: { open: string; close: string } | null;
}

export interface Reservation {
  id: string;
  tenant_id: string;
  zone_id: string;
  unit_id: string;
  resident_id: string;
  date: string;
  start_time: string;
  end_time: string;
  guests_count: number;
  status: ReservationStatus;
  payment_id: string | null;
  notes: string | null;
  created_at: string;
}

export interface ReservationGuest {
  id: string;
  reservation_id: string;
  full_name: string;
  document_number: string | null;
  created_at: string;
}

export interface Payment {
  id: string;
  tenant_id: string;
  unit_id: string;
  concept: "admin_fee" | "zone_reservation" | "penalty" | "other";
  description: string | null;
  amount_cop: number;
  due_date: string;
  paid_at: string | null;
  status: PaymentStatus;
  payment_ref: string | null;
  wompi_transaction_id: string | null;
  receipt_url: string | null;
  late_fee_cop: number;
  created_at: string;
}

export interface Package {
  id: string;
  tenant_id: string;
  unit_id: string;
  description: string;
  photo_url: string | null;
  received_by: string;
  received_at: string;
  delivered_at: string | null;
  delivered_to: string | null;
  signature_url: string | null;
  status: PackageStatus;
  created_at: string;
}

export interface Announcement {
  id: string;
  tenant_id: string;
  title: string;
  body: string;
  category: "general" | "maintenance" | "billing" | "event" | "emergency";
  created_by: string;
  is_pinned: boolean;
  attachments: string[];
  created_at: string;
  updated_at: string;
}

export interface Notification {
  id: string;
  tenant_id: string;
  user_id: string;
  type: "package" | "payment" | "announcement" | "visitor" | "reservation" | "pqr";
  title: string;
  body: string;
  data: Record<string, unknown>;
  read: boolean;
  created_at: string;
}

export interface Ticket {
  id: string;
  tenant_id: string;
  unit_id: string;
  resident_id: string;
  category: "maintenance" | "noise" | "security" | "billing" | "suggestion" | "other";
  subject: string;
  description: string;
  status: TicketStatus;
  rating: number | null;
  assigned_to: string | null;
  created_at: string;
  updated_at: string;
  resolved_at: string | null;
}

export interface TicketMessage {
  id: string;
  ticket_id: string;
  sender_id: string;
  message: string;
  attachments: string[];
  created_at: string;
}

export interface Visitor {
  id: string;
  tenant_id: string;
  unit_id: string;
  authorized_by: string;
  full_name: string;
  document_number: string | null;
  phone: string | null;
  reason: string | null;
  is_favorite: boolean;
  group_name: string | null;
  authorized_until: string | null;
  arrived_at: string | null;
  left_at: string | null;
  created_at: string;
}
